all:
  vars:
    ansible_user: "{{ lookup('env', 'NSO_DEVICES_USERNAME') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'NSO_DEVICES_PASSWORD') | default('cisco', true) }}"
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - site1
    regions:
      - org
  children:
    network:
      children:
        switches:
          vars:
            device_ned: cisco-nx-cli-5.23
          hosts:
            SW1:
              tags:
                - switch
            SW2:
              tags:
                - switch
            CORE1:
              tags:
                - switch
            R1:
              tags:
                - router
              
    org:
      children:
        site1:
          # vars:
          #   site_name: site1
          hosts:
            SW1:
            SW2:
            CORE1:
            R1:
            
