all:
  vars:
    ansible_user: "{{ lookup('env', 'NSO_DEVICES_USERNAME') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'NSO_DEVICES_PASSWORD') | default('cisco', true) }}"
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - site1
    regions:
      - org
  children:
    network:
      children:
        switches:
          vars:
            device_ned: cisco-nx-cli-5.23
          hosts:
            A1:
              tags:
                - switch
            A2:
              tags:
                - switch
            A3:
              tags:
                - switch   
            D1:
              tags:
                - switch                           
            D2:
              tags:
                - switch
            C1:
              tags:
                - switch
            C2:
              tags:
                - switch
            L1:
              tags:
                - switch
            L2:
              tags:
                - switch
            S1:
              tags:
                - switch
            S2:
              tags:
                - switch                
        routers:
          vars:
            device_ned: cisco-nx-cli-5.23
          hosts:
            R1:
              tags:
                - router
            R2:
              tags:
                - router
            DCR1:
              tags:
                - router
            
    org:
      children:
        site1:
          # vars:
          #   site_name: site1
          hosts:
            A1:
            A2:
            D1:
            D2:
            C1:
            C2:
            R1:
            R2:
            DCR1:
            S1:
            S2:
            L1:
            L2:
            
