all:
  vars:
    ansible_user: "{{ lookup('env', 'NSO_DEVICES_USERNAME') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'NSO_DEVICES_PASSWORD') | default('cisco', true) }}"
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - site1
    regions:
      - org
  children:
    network:
      children:
        switches:
          vars:
            device_ned: cisco-nx-cli-5.25
          hosts:
            n9kv1:
              tags:
                - switch
            n9kv2:
              tags:
                - switch
    org:
      children:
        site1:
          # vars:
          #   site_name: site1
          hosts:
            n9kv1:
            n9kv2:
