all:
  vars:
    ansible_user: "{{ lookup('env', 'NSO_DEVICES_USERNAME') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'NSO_DEVICES_PASSWORD') | default('cisco', true) }}"
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - site1
    regions:
      - org
  children:
    network:
      children:
        switches:
          vars:
            os: iosxe
            device_ned: cisco-nx-cli-5.23
          hosts:
            A1:
              ansible_host: 10.0.0.4
              tags:
                - switch
            A2:
              ansible_host: 10.0.0.5
              tags:
                - switch
            A3:
              ansible_host: 10.0.0.6
              tags:
                - switch   
            D1:
              ansible_host: 10.0.0.80
              tags:
                - l3switch                           
            D2:
              ansible_host: 10.0.0.81
              tags:
                - l3switch
            C1:
              ansible_host: 10.0.0.78
              tags:
                - l3switch
            C2:
              ansible_host: 10.0.0.79
              tags:
                - l3switch
        dc_switches:
          vars:
            os: nxos
            device_ned: cisco-nx-cli-5.23
          hosts:
            L1:
              ansible_host: 20.0.0.3
              os: nxos
              tags:
                - switch
            L2:
              ansible_host: 20.0.0.4
              os: nxos
              tags:
                - dc_switch
            S1:
              ansible_host: 20.0.0.1
              os: nxos
              tags:
                - dc_switch
            S2:
              ansible_host: 20.0.0.2
              os: nxos
              tags:
                - dc_switch                
        routers:
          vars:
            os: iosxe
            device_ned: cisco-nx-cli-5.23
          hosts:
            R1:
              ansible_host: 10.0.0.76
              tags:
                - router
            R2:
              ansible_host: 10.0.0.77
              tags:
                - router
            DCR1:
              ansible_host: 20.0.0.5
              tags:
                - router
            
    org:
      children:
        campus_rtp:
          # vars:
          #   site_name: site1
          hosts:
            A1:
            A2:
            A3:
            D1:
            D2:
            C1:
            C2:
            R1:
            R2:
        dc_rtp:
          # vars:
          #   site_name: site1
          hosts:
            DCR1:
            S1:
            S2:
            L1:
            L2:
            
