all:
  vars:

    # If you are using remote files, set nso_remote_src to True
    # nso_remote_src: True
    # nso_installer_file: https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/nso-6.1.linux.x86_64.signed.bin
    # nso_ned_files:
    #   - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.1-cisco-ios-6.92.7.signed.bin
    #   - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.1-cisco-nx-5.23.13.signed.bin
    #   - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.1-cisco-iosxr-7.49.2.signed.bin
    #   - https://colabucket.s3.amazonaws.com/sw/cisco/nso/6.1/ncs-6.0.3-cisco-asa-6.18.3.signed.bin

    # If you are using local files, set nso_remote_src to False
    nso_remote_src: False
    nso_installer_file: "file://{{ lookup('env', 'PWD') }}/packages/nso-6.2-freetrial.linux.x86_64.signed.bin"
    nso_ned_files:
      - "file://{{ lookup('env', 'PWD') }}/packages/ncs-6.2-cisco-ios-6.103-freetrial.signed.bin"
      - "file://{{ lookup('env', 'PWD') }}/packages/ncs-6.2-cisco-nx-5.25.6-freetrial.signed.bin"

    nso_default_ned: cisco-ios-cli-6.103

    nso_auth_groups:
      default:
        remote_name: admin
        remote_password: cisco
        remote_secondary_password: cisco

    # If additional ubuntu packages are required, add them here
    nso_package_requirements:
      - openjdk-19-jdk
      - openssh-client
      - ant
      - make
      - libxml2-utils
      - xsltproc

  children:
    nso:
      vars:
        ansible_user: "{{ lookup('env', 'NSO_USERNAME') | default('ubuntu', true) }}"
        ansible_password: "{{ lookup('env', 'NSO_PASSWORD') | default('admin', true) }}"
        ansible_python_interpreter: /usr/bin/python3
      hosts:
        nso1:
